### ISSUE TITLE
Click on list item title ends with List item not found message

### ISSUE THREAD

**Issue by lexislav** [dutchheight/craft-navie#8]
I supose that click on list's item should go to list item detail/edit page.
But it ends up with not found message.

**Comment by freimutt** [comment]
Could you provide more information about your setup. I cannot reproduce your issue.

**Comment by lexislav** [comment]
I will start with the error page, if it helps:

```
yii\web\NotFoundHttpException: List item not found. in /Users/lexislav/Websites/koma-family.cz/vendor/dutchheight/craft-navie/src/controllers/ListsController.php:598
Stack trace:
#0 /Users/lexislav/Websites/koma-family.cz/vendor/dutchheight/craft-navie/src/controllers/ListsController.php(228): dutchheight\navie\controllers\ListsController->prepEditListItemVariables(Array)
#1 [internal function]: dutchheight\navie\controllers\ListsController->actionEditListItem('mainMenu', NULL, 30197, NULL)
#2 /Users/lexislav/Websites/koma-family.cz/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/lexislav/Websites/koma-family.cz/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/lexislav/Websites/koma-family.cz/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('edit-list-item', Array)
#5 /Users/lexislav/Websites/koma-family.cz/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-list-item', Array)
#6 /Users/lexislav/Websites/koma-family.cz/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('navie/lists/edi...', Array)
#7 /Users/lexislav/Websites/koma-family.cz/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('navie/lists/edi...', Array)
#8 /Users/lexislav/Websites/koma-family.cz/vendor/craftcms/cms/src/web/Application.php(275): yii\web\Application->handleRequest(Object(craft\web\Request))
#9 /Users/lexislav/Websites/koma-family.cz/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/lexislav/Websites/koma-family.cz/web/index.php(21): yii\base\Application->run()
#11 {main}
```

But it is true that I am getting this only on one site. On other on the same (local) machine Navie works just fine.

**Comment by lexislav** [comment]
I did some testing: the error occurs for lists created with „Propagate list items across all enabled sites?“ checkbox unchecked.

Edit: and only when editing list on other domain then primary (if the primary domain is primary.com, the bug comes out when editing navie list on otherdomain.com)

**Comment by freimutt** [comment]
Could you try out the latest version, let me know if it fixed your issue.

**Comment by lexislav** [comment]
Yes, the issue is foexd now. Thanks. I believe the Navie is best option for navigation.
